### ISSUE TITLE
How to deploy in real recommender systems

### ISSUE THREAD

**Issue by weilonghu** [archersama/IntTower#2]
I have several questions:
1. As I known, faiss does not support 'max' operation.
2. Fot i-th layer user representaion, we will compute each head pairwise to get the similarity score, So we need to retrieve H^2 times？If there are L layers, eventually we need to retrieve L* H^2 times?

Thanks!

**Comment by archersama** [comment]
thank your question.
1.we just save and get item embedding in faiss, 'max' operation is conducted in inference code.
2.In our code, for all heads,  the Fe score is done in a parallel way. For a single layer, it only needs once to compute similarity score. For L layers, we only compute L times.

And in online inference, we find that only using last layer to compute  MaxSim Score is also useful, so you can use last layer to 
compute MaxSim score to get the similarity score.

**Comment by weilonghu** [comment]
> 

Thanks for your reply, I'll try it later

**Comment by archersama** [comment]
It's ok, feel free to ask questions
