### ISSUE TITLE
Could you share the serving code?

### ISSUE THREAD

**Issue by thinkwee** [archersama/IntTower#3]
Thanks for your great job! I wonder if you can provide the example code on how to deploy the IntTower in real scenario? such as how to execute the multi-head faiss and maxsim in a parallel way.

**Comment by archersama** [comment]
For company privacy, we can't provide serving code. We don't use faiss to compute maxsim score, we have our own container to save embedding,and maxsim score is computed out of container. To compute maxsim score in a parallel way, just add FE-layer in user every layer and item tower last layer and compute maxsim score. In our code ,the multi head maxsim score is computed in a parallel way
  ```python
self.Fe_linears = nn.ModuleList(
            [nn.Linear(hidden_units[i], self.field_dim*self.user_head) for i in range(len(hidden_units) - 1)])
 ```
  ```python
def fe_score(user_rep, item_rep, user_fea_col, item_fea_col, user_embedding_dim, item_embedding_dim):
    score = []
    for i in range(len(user_embedding_dim)):
      user_temp = torch.reshape(user_rep[i], (-1, user_fea_col, user_embedding_dim[i]))
      item_temp = torch.reshape(item_rep[-1], (-1, item_fea_col, item_embedding_dim[i]))
      score.append((user_temp @ item_temp.permute(0, 2, 1)).max(2).values.sum(1))
    score = torch.stack(score).transpose(1, 0)
    return torch.sum(score, 1)
  ```

**Comment by thinkwee** [comment]
got it. thx for your reply~
