### ISSUE TITLE
矩阵相乘求相似度

### ISSUE THREAD

**Issue by lxx1884896** [archersama/IntTower#5]
您好，请教一下，下面的图中，函数fe_score()内部item_temp和user_tmep矩阵相乘是用来求向量相似度的对吧，但好像没看到在什么地方把item_temp和user_tmep中内部的向量给归一化到0-1之间
![image](https://github.com/archersama/IntTower/assets/26270928/d0565d6b-e67e-4853-b1d0-9c9a7aabd558)

**Comment by archersama** [comment]
直接使用即可，不需要归一化至0-1之间
