### ISSUE TITLE
多目标serving时的融合

### ISSUE THREAD

**Issue by lxx1884896** [archersama/IntTower#6]
您好，请教一下，如果我的粗排有多个目标，比如，ctr,cvr,   想问一下在预测时如何进行融合，目前我想到的，
1、 使用multi-head分别对ctr塔和cvr塔的顶部进行提取，将提取得到的ctr embedding以及cvr embedding分别和multi-head提取的user embedding过一遍fe_score函数，然后将 ctr的fe_score和cvr的fe_score 以一定权重进行融合，得到最终的score
2、使用multi-head分别对ctr塔和cvr塔的顶部进行提取，将提取得到的ctr embedding以及cvr embedding以一定权重进行融合，将融合后的embedding 和multi-head提取的user embedding过一遍fe_score函数，得到最终的score
谢谢~

**Comment by archersama** [comment]
我觉得第一种好一些，你可以通过实验测试一下
