### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by ymh-ymh** [archersama/IntTower#7]
>RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 23.99 GiB total capacity; 37.27 GiB already allocated; 0 bytes free; 37.33 GiB reserved in total by PyTorch)

I run this code on 24G GPU, this error always happened after epoch 2 whatever batch_size I set, is there anything wrong with my [environment](https://zhuanlan.zhihu.com/p/661649530)?

**Comment by archersama** [comment]
which python script do you use? I think it has nothing to do with the environment. Maybe more detailed information you can provide

**Comment by ymh-ymh** [comment]
I take `python3.10.12` as my interpreter. should I change the python version?

**Comment by archersama** [comment]
use this， https://github.com/archersama/IntTower/blob/main/requirements.txt ，and try python3.7
