### ISSUE TITLE
Question about serving the model

### ISSUE THREAD

**Issue by rfbr** [archersama/IntTower#8]
Hello!

First of all thanks a lot for your great article and for opening the code base.
I have a question regarding the model serving:
I understand that you create Faiss indices based on the multi-head latent representation of the items but how do you query them? Do you use the multi-head latent representation of the last layer of the user tower? And after retrieving the top K items, do you compute the Fe score to rerank the candidates?

**Comment by archersama** [comment]
we rewrote the code about faiss in our company platform，add fe score retrieval

**Comment by rfbr** [comment]
I see, thanks for the clarification!
